### ISSUE TITLE
Feature: sort html attributes

### ISSUE THREAD

**Issue by draylegend** [azat-io/eslint-plugin-perfectionist#302]
### Describe the rule

sort html attributes

### Before

```html
<form class="grid" (ngSubmit)="submit()" #f="ngForm">
  <input type="text" ngModel name="name" />
  <button>Submit</button>
</form>
```

### After

```html
<form #f="ngForm" (ngSubmit)="submit()" class="grid">
  <input name="name" ngModel type="text" />
  <button>Submit</button>
</form>
```

### Validations

- [X] Read the [docs](https://perfectionist.dev).
- [X] Check that there isn't [already an issue](https://github.com/azat-io/eslint-plugin-perfectionist/issues) that reports the same bug to avoid creating a duplicate.

**Comment by hugop95** [comment]
Hi @draylegend .

For info, Angular ESLint (https://github.com/angular-eslint/angular-eslint/tree/main) supports a template rule `attributes-order` (https://github.com/angular-eslint/angular-eslint/blob/main/packages/eslint-plugin-template/docs/rules/attributes-order.md) that does what you want and is auto-fixable.

Based on #175 which aims to deprecate framework rules, I don't know if @azat-io wishes to add Angular-related sorting rules.

**Comment by azat-io** [comment]
Hello, thank you for your issue!

That's right, like @hugop95 said, we don't plan to support things specific to frameworks. We only support JavaScript and TypeScript.

I recommend you to check out the corresponding ESLint plugin for Angular.

**Comment by draylegend** [comment]
perfectionist does already have sorting for svelte & vue.

![image](https://github.com/user-attachments/assets/f1eab385-b4ab-4b98-9083-d4890e00b55d)

That's why I was curious about angular support.

Another reason why I did create this issue was the problem with `@angular-eslint/template/attributes-order`. Id didn't work.

### Error

```js
Error: Error while loading rule '@angular-eslint/template/attributes-order': You have used a rule which requires '@angular-eslint/template-parser' to be used as the 'parser' in your ESLint config.
Occurred while linting /home/dl/my-project/apps/admin/src/app/app.component.ts

Error: Error while loading rule '@angular-eslint/template/attributes-order': You have used a rule which requires '@angular-eslint/template-parser' to be used as the 'parser' in your ESLint config.
Occurred while linting /home/dl/my-project/apps/admin/src/app/app.component.ts
at ensureTemplateParser (/home/dl/my-project/node_modules/@angular-eslint/utils/dist/eslint-plugin-template/parser-services.js:22:15)
at getTemplateParserServices (/home/dl/my-project/node_modules/@angular-eslint/utils/dist/eslint-plugin-template/parser-services.js:6:5)
at create (/home/dl/my-project/node_modules/@angular-eslint/eslint-plugin-template/dist/rules/attributes-order.js:65:70)
at Object.create (/home/dl/my-project/node_modules/@angular-eslint/eslint-plugin-template/dist/utils/create-eslint-rule.js:20:24)
at createRuleListeners (/home/dl/my-project/node_modules/eslint/lib/linter/linter.js:943:21)
at /home/dl/my-project/node_modules/eslint/lib/linter/linter.js:1068:84
at Array.forEach (
<anonymous>)
  at runRules (/home/dl/my-project/node_modules/eslint/lib/linter/linter.js:999:34)
  at #flatVerifyWithoutProcessors (/home/dl/my-project/node_modules/eslint/lib/linter/linter.js:1914:31)
  at Linter._verifyWithFlatConfigArrayAndWithoutProcessors
  (/home/dl/my-project/node_modules/eslint/lib/linter/linter.js:1995:49)
  Process finished with exit code -1
```

### ~/my-project/eslint.config.js

```js
const eslint = require('@eslint/js');
const nx = require('@nx/eslint-plugin');
const angular = require('angular-eslint');
const perfectionist = require('eslint-plugin-perfectionist');
const unusedImports = require('eslint-plugin-unused-imports');
const tseslint = require('typescript-eslint');

module.exports = tseslint.config(
  ...nx.configs['flat/base'],
  ...nx.configs['flat/typescript'],
  ...nx.configs['flat/javascript'],
  { ignores: ['**/dist'] },
  {
    extends: [
      eslint.configs.recommended,
      ...tseslint.configs.recommended,
      ...tseslint.configs.stylistic,
      ...angular.configs.tsRecommended,
    ],
    files: ['**/*.ts'],
    plugins: {
      '@angular-eslint/template': angular.templatePlugin,
      'unused-imports': unusedImports,
    },
    processor: angular.processInlineTemplates,
    rules: {
      '@angular-eslint/component-selector': [
        'error',
        { prefix: 'ff', style: 'kebab-case', type: 'element' },
      ],
      '@angular-eslint/directive-selector': [
        'error',
        { prefix: 'ff', style: 'camelCase', type: 'attribute' },
      ],
      '@angular-eslint/prefer-on-push-component-change-detection': 'error',
      '@angular-eslint/template/attributes-order': 'error',
      '@nx/enforce-module-boundaries': [
        'error',
        {
          allow: ['^.*/eslint(\\.base)?\\.config\\.[cm]?js$'],
          depConstraints: [{ onlyDependOnLibsWithTags: ['*'], sourceTag: '*' }],
          enforceBuildableLibDependency: true,
        },
      ],
      'no-unused-vars': 'off', // or "@typescript-eslint/no-unused-vars": "off",
      'unused-imports/no-unused-imports': 'error',
      'unused-imports/no-unused-vars': [
        'warn',
        {
          args: 'after-used',
          argsIgnorePattern: '^_',
          vars: 'all',
          varsIgnorePattern: '^_',
        },
      ],
    },
  },
  perfectionist.configs['recommended-natural'],
  {
    extends: [
      ...angular.configs.templateRecommended,
      ...angular.configs.templateAccessibility,
    ],
    files: ['**/*.html'],
  },
);
```

Please help me to understand the root cause of the problem. Thanks in advance <3

**Comment by hugop95** [comment]
@draylegend 
1. Remove the `'@angular-eslint/template': angular.templatePlugin` and  `'@angular-eslint/template/attributes-order': 'error'` lines. Keep `processor: angular.processInlineTemplates`.
2. Add a rule section with `'@angular-eslint/template/attributes-order': 'error'` in the HTML related-configuration at the bottom

Refer to https://github.com/angular-eslint/angular-eslint/blob/main/docs/CONFIGURING_FLAT_CONFIG.md, `files: ['**/*.html'],` section:
>   // Everything in this config object targets our HTML files (external templates,
    // and inline templates as long as we have the `processor` set on our TypeScript config above)

If this still doesn't work, I invite you to create a issue in the https://github.com/angular-eslint/angular-eslint/issues repository, you will get better support here.

**Comment by draylegend** [comment]
@hugop95 @azat-io thank you for your suggestions! I solved it as follows:

```mjs
// apps/admin/eslint.config.mjs

import nx from '@nx/eslint-plugin';
import { config } from 'typescript-eslint';

import baseConfig from '../../eslint.config.mjs';

export default config(
  ...baseConfig,
  ...nx.configs['flat/angular'],
  ...nx.configs['flat/angular-template'],
  {
    files: ['**/app.component.ts'],
    rules: {
      '@angular-eslint/component-selector': 'off',
    },
  },
  {
    files: ['**/*.html'],
    rules: {
      '@angular-eslint/template/attributes-order': [
        'error',
        { alphabetical: true },
      ],
    },
  },
);
```
