### ISSUE TITLE
Bug: SyntaxError: Invalid regular expression: /~/**/: Nothing to repeat

### ISSUE THREAD

**Issue by stevensacks** [azat-io/eslint-plugin-perfectionist#381]
### Describe the bug

After upgrading to 4.0.1. I get this error.
```ts
SyntaxError: Invalid regular expression: /~/**/: Nothing to repeat
Occurred while linting /Users/me/project/app/hooks/useClickOutside.ts:1
Rule: "perfectionist/sort-imports"

SyntaxError: Invalid regular expression: /~/**/: Nothing to repeat
Occurred while linting /Users/me/project/app/hooks/useClickOutside.ts:1
Rule: "perfectionist/sort-imports"
    at new RegExp (<anonymous>)
    at Module.matches (/Users/me/project/node_modules/eslint-plugin-perfectionist/dist/utils/matches.js:3:35)
    at /Users/me/project/node_modules/eslint-plugin-perfectionist/dist/rules/sort-imports.js:172:57
    at Array.some (<anonymous>)
    at matchesInternalPattern (/Users/me/project/node_modules/eslint-plugin-perfectionist/dist/rules/sort-imports.js:172:33)
    at registerNode (/Users/me/project/node_modules/eslint-plugin-perfectionist/dist/rules/sort-imports.js:233:39)
    at ruleErrorHandler (/Users/me/project/node_modules/eslint/lib/linter/linter.js:1076:28)
    at /Users/me/project/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/Users/me/project/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
Process finished with exit code -1
```

### Code example

No problem with latest 3.x build but 4.0.1 crashes on every file.

### ESLint version

8.57.0

### ESLint Plugin Perfectionist version

4.0.1

### Validations

- [X] Read the [docs](https://perfectionist.dev).
- [X] Check that there isn't [already an issue](https://github.com/azat-io/eslint-plugin-perfectionist/issues) that reports the same bug to avoid creating a duplicate.

**Comment by azat-io** [comment]
Sorry it's our problem.

**Comment by stevensacks** [comment]
Looks like the internalPattern was changed from:
```
internalPattern: ['~/**']
``` 
to
```
internalPattern: ['^~/.*'],
```

This fixed it.

**Comment by stevensacks** [comment]
It looks like the previous internalPattern setting `['~/**']` is no longer valid. My project is remix, which uses `~` tilde as the prefix for internal packages.

Here is my rule configuration. I want react types and then react packages to always come first. When I change the internalPattern to the new default `['^~/.*']`, it sorts external packages that start with `@` before everything.

```ts
'perfectionist/sort-imports': [
  'error',
  {
    type: 'natural',
    internalPattern: ['~/**'],
    newlinesBetween: 'never',
    groups: [
      'react-type',
      'react',
      'react-other-type',
      'react-other',
      ['external-type', 'external'],
      ['builtin-type', 'builtin'],
      ['internal-type', 'internal'],
      ['parent-type', 'parent'],
      ['sibling-type', 'sibling'],
      ['index-type', 'index'],
      'side-effect',
      ['object', 'unknown'],
      'style',
    ],
    customGroups: {
      value: {
        react: ['react'],
        'react-other': ['react-*'],
      },
      type: {
        'react-type': ['react'],
        'react-other-type': ['react-*'],
      },
    },
  },
],
```

This seems to me to be a bug since the [custom group docs](https://perfectionist.dev/rules/sort-imports#customgroups) state that you can put react first, but the default internalPattern regex does not honor the group order.

**Comment by alfaproject** [comment]
We've also got this error:
```
SyntaxError: Invalid regular expression: /=== ** ===/: Nothing to repeat
```

Rule definition:
```
'perfectionist/sort-enums': ['error', { partitionByComment: '=== ** ===' }],
```

**Comment by hugop95** [comment]
Hi @alfaproject 
`**` is not a valid regular expression. The error is expected.
