### ISSUE TITLE
Bug: Error while loading rule 'perfectionist/sort-svelte-attributes': The "path" argument must be of type string. 

### ISSUE THREAD

**Issue by gdh51** [azat-io/eslint-plugin-perfectionist#94]
### Describe the bug

npm version: 2.5.0

error info: [Error - 02:14:58] TypeError: Error while loading rule 'perfectionist/sort-svelte-attributes': The "path" argument must be of type string. Received undefined
Occurred while linting /Users/bytedance/Desktop/poi-zetton/packages/util/trade-sdk/src/lynx/index.ts
    at new NodeError (node:internal/errors:399:5)
    at validateString (node:internal/validators:163:11)
    at Object.extname (node:path:1380:5)
    at create (/Users/bytedance/Desktop/poi-zetton/node_modules/.pnpm/eslint-plugin-perfectionist@2.5.0_typescript@5.0.4/node_modules/eslint-plugin-perfectionist/dist/index.js:1:3917)
    at Object.create (/Users/bytedance/Desktop/poi-zetton/node_modules/.pnpm/@typescript-eslint+utils@6.13.1_typescript@5.0.4/node_modules/@typescript-eslint/utils/dist/eslint-utils/RuleCreator.js:38:20)
    at createRuleListeners (/Users/bytedance/Desktop/poi-zetton/node_modules/.pnpm/eslint@8.20.0/node_modules/eslint/lib/linter/linter.js:922:21)
    at /Users/bytedance/Desktop/poi-zetton/node_modules/.pnpm/eslint@8.20.0/node_modules/eslint/lib/linter/linter.js:1104:110
    at Array.forEach (<anonymous>)
    at runRules (/Users/bytedance/Desktop/poi-zetton/node_modules/.pnpm/eslint@8.20.0/node_modules/eslint/lib/linter/linter.js:1041:34)
    at Linter._verifyWithoutProcessors (/Users/bytedance/Desktop/poi-zetton/node_modules/.pnpm/eslint@8.20.0/node_modules/eslint/lib/linter/linter.js:1393:31)
    at Linter._verifyWithConfigArray (/Users/bytedance/Desktop/poi-zetton/node_modules/.pnpm/eslint@8.20.0/node_modules/eslint/lib/linter/linter.js:1757:21)
    at Linter.verify (/Users/bytedance/Desktop/poi-zetton/node_modules/.pnpm/eslint@8.20.0/node_modules/eslint/lib/linter/linter.js:1475:65)
    at Linter.verifyAndFix (/Users/bytedance/Desktop/poi-zetton/node_modules/.pnpm/eslint@8.20.0/node_modules/eslint/lib/linter/linter.js:2004:29)
    at verifyText (/Users/bytedance/Desktop/poi-zetton/node_modules/.pnpm/eslint@8.20.0/node_modules/eslint/lib/cli-engine/cli-engine.js:245:48)
    at CLIEngine.executeOnText (/Users/bytedance/Desktop/poi-zetton/node_modules/.pnpm/eslint@8.20.0/node_modules/eslint/lib/cli-engine/cli-engine.js:917:26)
    at ESLint.lintText (/Users/bytedance/Desktop/poi-zetton/node_modules/.pnpm/eslint@8.20.0/node_modules/eslint/lib/eslint/eslint.js:592:23)
    at /Users/bytedance/.vscode/extensions/dbaeumer.vscode-eslint-2.4.2/server/out/eslintServer.js:1:24860
    at E (/Users/bytedance/.vscode/extensions/dbaeumer.vscode-eslint-2.4.2/server/out/eslintServer.js:1:19218)
    at e.validate (/Users/bytedance/.vscode/extensions/dbaeumer.vscode-eslint-2.4.2/server/out/eslintServer.js:1:24819)
    at /Users/bytedance/.vscode/extensions/dbaeumer.vscode-eslint-2.4.2/server/out/eslintServer.js:1:221494

### Code example

eslintrc.js is 

```js
module.exports = {
  root: true,
  extends: [ 'plugin:perfectionist/recommended-natural'],

  plugins: ['perfectionist'],
  parserOptions: {
    project: true,
    tsconfigRootDir: __dirname
  },
  rules: {
    'perfectionist/sort-imports': [
      'error',
      {
        type: 'natural',
        order: 'asc',
        groups: [
          'type',
          'react',
          'nanostores',
          ['builtin', 'external'],
          'internal-type',
          'internal',
          ['parent-type', 'sibling-type', 'index-type'],
          ['parent', 'sibling', 'index'],
          'side-effect',
          'style',
          'object',
          'unknown'
        ],
        'newlines-between': 'always',
        'internal-pattern': ['@/components/**', '@/stores/**', '@/pages/**', '@/lib/**']
      }
    ]
  }
};

```

### ESLint version

v8.20.0

### ESLint Plugin Perfectionist version

v2.5.0

### Validations

- [X] Read the [docs](https://eslint-plugin-perfectionist.azat.io).
- [X] Check that there isn't [already an issue](https://github.com/azat-io/eslint-plugin-perfectionist/issues) that reports the same bug to avoid creating a duplicate.

**Comment by azat-io** [comment]
Hi. Thank you for your issue. Do you have the ability to create a repository to reproduce the issue?

**Comment by hckhanh** [comment]
I figured out that everything is normal until I put the repo to a monorepo. I get this case too.

**Comment by azat-io** [comment]
Can you show me your package.json?

Reproducing the problem would help speed up the resolution.

**Comment by hckhanh** [comment]
Hi @azat-io, here is the repo. You can add eslint-plugin-perfectionist

https://github.com/hckhanh/demo-sentry

**Comment by azat-io** [comment]
@hckhanh Thank you! Could you please describe steps to reproduce the problem?

Because I don't see ESLint config in project root or scripts to call it.

**Comment by hckhanh** [comment]
Sorry about that, it seems there are some problems with my WebStorm. Everything is fine now.

**Comment by azat-io** [comment]
No problem. Thank you for your issue!

**Comment by Lighttree** [comment]
I have the same issue after upgrading from `2.2.0` to `2.5.0`. It seems that there were also some issues in `2.4.1`:

```
Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/viktorbusko/Development/html-promos/node_modules/eslint-plugin-perfectionist/dist/index.js from /Users/viktorbusko/Development/html-promos/node_modules/@eslint/eslintrc/lib/config-array-factory.js not supported.
index.js is treated as an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which declares all .js files in that package scope as ES modules.
```

And then this one `Error while loading rule 'perfectionist/sort-svelte-attributes': The "path" argument must be of type string`.

Not sure about the reason trying to dig around. Maybe ESLint is outdated.

**Comment by azat-io** [comment]
@Lighttree Can you reproduce the problem and provide a link to the repository? I'd be interested in looking at and researching this.

**Comment by hoshikitsunoda** [comment]
I got the same error (`TypeError: Error while loading rule 'perfectionist/sort-svelte-attributes': The "path" argument must be of type string. Received undefined`), and the culprit was the ESlint version. Upgrading from 8.4.1 -> the latest fixed the issue.
